- name: Add the new user 'kali'
  hosts: debian3
  become: true
  tasks:
    - name: Change root password
      user:
        name: root
        password: $6$Tu5ieXBSZfxfVfSb$8VEFTMXpJt1VUrhAIujptxFt79dw/bymV5dCwOKIdPum5oDZ2nVKpZunBVb.gDbrUkTi7FFnmn4I95bpALaDb0
    - name: Change admin password
      user:
        name: admin
        password: $6$tQ/92PapJj9lgqRm$KaAQAMTAxHQfuvVg4CdBKaFayy8CZ1Bpq7Gv8Im6VRE3Of8yu1UImJMH12xCUYnDNXwlIwR1pNhEqgSGTtjhX/
